spring:
  datasource:
    url: jdbc:mysql://localhost:3306/acegear_authentication?autoReconnect=TRUE&useUnicode=TRUE&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    test-on-borrow: true
    validation-query: SELECT 1
    dbcp2:
      test-on-borrow: true
      validation-query: SELECT 1
    type: org.apache.commons.dbcp2.BasicDataSource
  jpa:
    hibernate:
      ddl-auto: create-drop

---

spring:
  profiles: production
  datasource:
    url: jdbc:mysql://10.10.82.107:3306/acegear_cms?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: acegear_cms
    password: acegear_cms
    driver-class-name: com.mysql.jdbc.Driver
    test-on-borrow: true
    validation-query: SELECT 1
    dbcp2:
      test-on-borrow: true
      validation-query: SELECT 1
    type: org.apache.commons.dbcp2.BasicDataSource
  jpa:
    hibernate:
      ddl-auto: validate
